// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tDcLAAzBYxMBQFp3GHSHfW
// Component: cm3P6MJlYR
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_brands_beats.module.css"; // plasmic-import: tDcLAAzBYxMBQFp3GHSHfW/projectcss
import * as sty from "./PlasmicContentAboutus.module.css"; // plasmic-import: cm3P6MJlYR/css

export type PlasmicContentAboutus__VariantMembers = {};

export type PlasmicContentAboutus__VariantsArgs = {};
type VariantPropType = keyof PlasmicContentAboutus__VariantsArgs;
export const PlasmicContentAboutus__VariantProps = new Array<VariantPropType>();

export type PlasmicContentAboutus__ArgsType = {};
type ArgPropType = keyof PlasmicContentAboutus__ArgsType;
export const PlasmicContentAboutus__ArgProps = new Array<ArgPropType>();

export type PlasmicContentAboutus__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultContentAboutusProps {
  className?: string;
}

function PlasmicContentAboutus__RenderFunc(props: {
  variants: PlasmicContentAboutus__VariantsArgs;
  args: PlasmicContentAboutus__ArgsType;
  overrides: PlasmicContentAboutus__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__qjPoV)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box___9BNcP
          )}
        >
          {"Qué es Brands Beats"}
        </div>
      </div>

      <div className={classNames(defaultcss.all, sty.box__gxMtJ)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__jrkDi
          )}
        >
          {
            "Hay varias características comunes a todas las DTC: la necesidad de crear algo propio, el canal para expresar ideas creativas y la búsqueda de la libertad.\nLa única forma posible de poner en práctica estas tres cosas es creando un negocio; un negocio con diseños, productos y marca propios.\nSabemos la dificultad que hay detrás de hacer que un negocio sea rentable. La rentabilidad depende de vender, vender depende de que te conozcan y que te conozcan depende de canales saturados y caros.\nBrands Beats pretende ser un canal nuevo para conocer y encontrar marcas DTC. Los canales actuales están basados en la reactividad que produce el impacto con anuncios. Cuando soy impactado con algo que no esperaba a eso lo llamamos ruido. Brands Beats es un canal basado en la proactividad del consumidor y en sus búsquedas conscientes.\nSi cada vez más buscamos comprar con consciencia, tiene sentido empezar a ser conscientes en la propia búsqueda. ¿No crees?"
          }
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContentAboutus__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicContentAboutus__VariantsArgs;
  args?: PlasmicContentAboutus__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicContentAboutus__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicContentAboutus__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicContentAboutus__ArgProps,
      internalVariantPropNames: PlasmicContentAboutus__VariantProps
    });

    return PlasmicContentAboutus__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContentAboutus";
  } else {
    func.displayName = `PlasmicContentAboutus.${nodeName}`;
  }
  return func;
}

export const PlasmicContentAboutus = Object.assign(
  // Top-level PlasmicContentAboutus renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicContentAboutus
    internalVariantProps: PlasmicContentAboutus__VariantProps,
    internalArgProps: PlasmicContentAboutus__ArgProps
  }
);

export default PlasmicContentAboutus;
/* prettier-ignore-end */
