// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tDcLAAzBYxMBQFp3GHSHfW
// Component: 5FtszvpDSt
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_brands_beats.module.css"; // plasmic-import: tDcLAAzBYxMBQFp3GHSHfW/projectcss
import * as sty from "./PlasmicPretest.module.css"; // plasmic-import: 5FtszvpDSt/css

export type PlasmicPretest__VariantMembers = {};

export type PlasmicPretest__VariantsArgs = {};
type VariantPropType = keyof PlasmicPretest__VariantsArgs;
export const PlasmicPretest__VariantProps = new Array<VariantPropType>();

export type PlasmicPretest__ArgsType = {
  brandName?: React.ReactNode;
  brandImage?: React.ReactNode;
};

type ArgPropType = keyof PlasmicPretest__ArgsType;
export const PlasmicPretest__ArgProps = new Array<ArgPropType>(
  "brandName",
  "brandImage"
);

export type PlasmicPretest__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
  img?: p.Flex<"img">;
};

export interface DefaultPretestProps {
  brandName?: React.ReactNode;
  brandImage?: React.ReactNode;
  className?: string;
}

function PlasmicPretest__RenderFunc(props: {
  variants: PlasmicPretest__VariantsArgs;
  args: PlasmicPretest__ArgsType;
  overrides: PlasmicPretest__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, sty.box)}
      >
        <p.PlasmicSlot
          defaultContents={
            <img
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(defaultcss.img, sty.img)}
              role={"img"}
            />
          }
          value={args.brandImage}
        />

        <p.PlasmicSlot
          defaultContents={"Enter some text"}
          value={args.brandName}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box", "img"],
  box: ["box", "img"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
  img: "img";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPretest__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicPretest__VariantsArgs;
  args?: PlasmicPretest__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicPretest__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicPretest__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPretest__ArgProps,
      internalVariantPropNames: PlasmicPretest__VariantProps
    });

    return PlasmicPretest__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPretest";
  } else {
    func.displayName = `PlasmicPretest.${nodeName}`;
  }
  return func;
}

export const PlasmicPretest = Object.assign(
  // Top-level PlasmicPretest renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicPretest
    internalVariantProps: PlasmicPretest__VariantProps,
    internalArgProps: PlasmicPretest__ArgProps
  }
);

export default PlasmicPretest;
/* prettier-ignore-end */
