// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tDcLAAzBYxMBQFp3GHSHfW
// Component: DheiKRFVbk
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_brands_beats.module.css"; // plasmic-import: tDcLAAzBYxMBQFp3GHSHfW/projectcss
import * as sty from "./PlasmicTestinput.module.css"; // plasmic-import: DheiKRFVbk/css

export type PlasmicTestinput__VariantMembers = {};

export type PlasmicTestinput__VariantsArgs = {};
type VariantPropType = keyof PlasmicTestinput__VariantsArgs;
export const PlasmicTestinput__VariantProps = new Array<VariantPropType>();

export type PlasmicTestinput__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicTestinput__ArgsType;
export const PlasmicTestinput__ArgProps = new Array<ArgPropType>("children");

export type PlasmicTestinput__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultTestinputProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicTestinput__RenderFunc(props: {
  variants: PlasmicTestinput__VariantsArgs;
  args: PlasmicTestinput__ArgsType;
  overrides: PlasmicTestinput__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.PlasmicSlot
        defaultContents={"Enter some text"}
        value={args.children}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestinput__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicTestinput__VariantsArgs;
  args?: PlasmicTestinput__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicTestinput__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicTestinput__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTestinput__ArgProps,
      internalVariantPropNames: PlasmicTestinput__VariantProps
    });

    return PlasmicTestinput__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestinput";
  } else {
    func.displayName = `PlasmicTestinput.${nodeName}`;
  }
  return func;
}

export const PlasmicTestinput = Object.assign(
  // Top-level PlasmicTestinput renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTestinput
    internalVariantProps: PlasmicTestinput__VariantProps,
    internalArgProps: PlasmicTestinput__ArgProps
  }
);

export default PlasmicTestinput;
/* prettier-ignore-end */
