// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tDcLAAzBYxMBQFp3GHSHfW
// Component: WLA_nd03-v
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import SobreNosotrosPage from "../../SobreNosotrosPage"; // plasmic-import: kdE_dd2jbPd/component
import RoutesDialog from "../../RoutesDialog"; // plasmic-import: DFJFHCaPCd/component
import DialogClickableText from "../../DialogClickableText"; // plasmic-import: E4MwO2Nk-p/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_brands_beats.module.css"; // plasmic-import: tDcLAAzBYxMBQFp3GHSHfW/projectcss
import * as sty from "./PlasmicDd.module.css"; // plasmic-import: WLA_nd03-v/css

export type PlasmicDd__VariantMembers = {};

export type PlasmicDd__VariantsArgs = {};
type VariantPropType = keyof PlasmicDd__VariantsArgs;
export const PlasmicDd__VariantProps = new Array<VariantPropType>();

export type PlasmicDd__ArgsType = {};
type ArgPropType = keyof PlasmicDd__ArgsType;
export const PlasmicDd__ArgProps = new Array<ArgPropType>();

export type PlasmicDd__OverridesType = {
  root?: p.Flex<typeof SobreNosotrosPage>;
};

export interface DefaultDdProps {
  className?: string;
}

function PlasmicDd__RenderFunc(props: {
  variants: PlasmicDd__VariantsArgs;
  args: PlasmicDd__ArgsType;
  overrides: PlasmicDd__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <SobreNosotrosPage
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: typeof SobreNosotrosPage;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDd__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicDd__VariantsArgs;
  args?: PlasmicDd__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicDd__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicDd__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicDd__ArgProps,
      internalVariantPropNames: PlasmicDd__VariantProps
    });

    return PlasmicDd__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDd";
  } else {
    func.displayName = `PlasmicDd.${nodeName}`;
  }
  return func;
}

export const PlasmicDd = Object.assign(
  // Top-level PlasmicDd renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicDd
    internalVariantProps: PlasmicDd__VariantProps,
    internalArgProps: PlasmicDd__ArgProps
  }
);

export default PlasmicDd;
/* prettier-ignore-end */
