// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tDcLAAzBYxMBQFp3GHSHfW
// Component: RmR6Z9n4oC
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_brands_beats.module.css"; // plasmic-import: tDcLAAzBYxMBQFp3GHSHfW/projectcss
import * as sty from "./PlasmicTectcomp.module.css"; // plasmic-import: RmR6Z9n4oC/css

export type PlasmicTectcomp__VariantMembers = {};

export type PlasmicTectcomp__VariantsArgs = {};
type VariantPropType = keyof PlasmicTectcomp__VariantsArgs;
export const PlasmicTectcomp__VariantProps = new Array<VariantPropType>();

export type PlasmicTectcomp__ArgsType = {};
type ArgPropType = keyof PlasmicTectcomp__ArgsType;
export const PlasmicTectcomp__ArgProps = new Array<ArgPropType>();

export type PlasmicTectcomp__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultTectcompProps {
  className?: string;
}

function PlasmicTectcomp__RenderFunc(props: {
  variants: PlasmicTectcomp__VariantsArgs;
  args: PlasmicTectcomp__ArgsType;
  overrides: PlasmicTectcomp__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTectcomp__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicTectcomp__VariantsArgs;
  args?: PlasmicTectcomp__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicTectcomp__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicTectcomp__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTectcomp__ArgProps,
      internalVariantPropNames: PlasmicTectcomp__VariantProps
    });

    return PlasmicTectcomp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTectcomp";
  } else {
    func.displayName = `PlasmicTectcomp.${nodeName}`;
  }
  return func;
}

export const PlasmicTectcomp = Object.assign(
  // Top-level PlasmicTectcomp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTectcomp
    internalVariantProps: PlasmicTectcomp__VariantProps,
    internalArgProps: PlasmicTectcomp__ArgProps
  }
);

export default PlasmicTectcomp;
/* prettier-ignore-end */
