// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wBcw9dcxKyU36yfsUviVdG
// Component: Ra6hYxqoFV
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: E1isZEegCA11/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_responsive_bb.module.css"; // plasmic-import: wBcw9dcxKyU36yfsUviVdG/projectcss
import * as sty from "./PlasmicExpandRoutesButton.module.css"; // plasmic-import: Ra6hYxqoFV/css

import FavoriteBlack18Dpsvg2Icon from "./icons/PlasmicIcon__FavoriteBlack18Dpsvg2"; // plasmic-import: qYjXe9EXdM/icon

export type PlasmicExpandRoutesButton__VariantMembers = {};

export type PlasmicExpandRoutesButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicExpandRoutesButton__VariantsArgs;
export const PlasmicExpandRoutesButton__VariantProps = new Array<VariantPropType>();

export type PlasmicExpandRoutesButton__ArgsType = {};
type ArgPropType = keyof PlasmicExpandRoutesButton__ArgsType;
export const PlasmicExpandRoutesButton__ArgProps = new Array<ArgPropType>();

export type PlasmicExpandRoutesButton__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultExpandRoutesButtonProps {
  className?: string;
}

function PlasmicExpandRoutesButton__RenderFunc(props: {
  variants: PlasmicExpandRoutesButton__VariantsArgs;
  args: PlasmicExpandRoutesButton__ArgsType;
  overrides: PlasmicExpandRoutesButton__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return ((hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={hasVariant(globalVariants, "screen", "mobile") ? true : false}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {(hasVariant(globalVariants, "screen", "mobile") ? true : false) ? (
        <FavoriteBlack18Dpsvg2Icon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(defaultcss.all, sty.svg)}
          role={"img"}
        />
      ) : null}
    </p.Stack>
  ) : null) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicExpandRoutesButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicExpandRoutesButton__VariantsArgs;
  args?: PlasmicExpandRoutesButton__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicExpandRoutesButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicExpandRoutesButton__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicExpandRoutesButton__ArgProps,
      internalVariantPropNames: PlasmicExpandRoutesButton__VariantProps
    });

    return PlasmicExpandRoutesButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicExpandRoutesButton";
  } else {
    func.displayName = `PlasmicExpandRoutesButton.${nodeName}`;
  }
  return func;
}

export const PlasmicExpandRoutesButton = Object.assign(
  // Top-level PlasmicExpandRoutesButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicExpandRoutesButton
    internalVariantProps: PlasmicExpandRoutesButton__VariantProps,
    internalArgProps: PlasmicExpandRoutesButton__ArgProps
  }
);

export default PlasmicExpandRoutesButton;
/* prettier-ignore-end */
