// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicHeaderSearchBar,
  DefaultHeaderSearchBarProps
} from "./plasmic/brands_beats/PlasmicHeaderSearchBar";
import algoliasearch from 'algoliasearch';
import {InstantSearch} from 'react-instantsearch-dom';
//import SearchContext from './SearchContext'

const searchClient = algoliasearch(
  'E5ACT1VI4D',
  '58c5723bb97942db9b754bf244b1da75'
);

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface HeaderSearchBarProps extends Omit<DefaultHeaderSearchBarProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultHeaderSearchBarProps altogether and have
// total control over the props for your component.
interface HeaderSearchBarProps extends DefaultHeaderSearchBarProps {}

function HeaderSearchBar(props: HeaderSearchBarProps) {
  return <InstantSearch searchClient={searchClient} indexName="brands_beats"><PlasmicHeaderSearchBar/></InstantSearch>;
}

export default HeaderSearchBar;
